# Generated by Django 5.2.5 on 2025-09-04 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_recurringexpense_next_run_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringexpense',
            name='next_run_at',
            field=models.DateField(default=datetime.date(2025, 9, 4)),
        ),
    ]
