# Generated by Django 5.2.5 on 2025-09-08 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_recurringexpense_next_run_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringexpense',
            name='next_run_at',
            field=models.DateField(default=datetime.date(2025, 9, 8)),
        ),
    ]
