# Generated by Django 5.2.5 on 2025-09-10 14:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_recurringexpense_next_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='expenses.category'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='next_run_at',
            field=models.DateField(default=datetime.date(2025, 9, 10)),
        ),
    ]
