# Generated by Django 5.2.5 on 2025-09-12 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2025, 9, 12)),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='next_run_at',
            field=models.DateField(default=datetime.date(2025, 9, 12)),
        ),
    ]
