# Generated by Django 5.2.5 on 2025-10-31 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_incomecategory_is_default_alter_incomecategory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 10, 31, 22, 48, 48, 864942), null=True),
        ),
    ]
